service: serverless-comprehend
variablesResolutionMode: 20210326
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  memorySize: 256
  stage: ${opt:stage, 'develop'}
  region: ${opt:region, 'eu-west-1'}
  environment:
    STAGE: ${opt:stage, self:provider.stage}
  apiGateway:
    shouldStartNameWithService: true
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "comprehend:DetectSentiment"
            - "comprehend:DetectPiiEntities"
          Resource:
            - "*"
# serverless plugins
plugins:
  - serverless-webpack
package:
  individually: true
functions:
  # function to add a new comment
  add-comment:
    handler: src/functions/add-comment/add-comment.handler
    timeout: 10
    events:
      - http:
          path: comments
          method: post
custom:
  # this is the webpack config for the build
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules:
      forceExclude:
        - aws-sdk
resources:
  Resources:
